### ISSUE TITLE
Have quickStartSecurity use a generated password

### ISSUE THREAD

**Issue by awisniew90** [OpenLiberty/application-stack#21]
Currently we have a default username and password configured in our starter via quickStartSecurity. We should consider using an auto generated password for the inner loop and removing the qss config when deploying in the outerloop.

**Comment by awisniew90** [comment]
I believe the generation happens at server create time, so we may run into a problem since we are creating the server in the base dev image.

**Comment by scottkurz** [comment]
@awisniew90  
> I believe the generation happens at server create time, so we may run into a problem since we are creating the server in the base dev image.

No, we're throwing away the server we created and only saving the OL install.

**Comment by scottkurz** [comment]
Done.
