### ISSUE TITLE
Create a sample use devfile 2.2 to get Open Liberty displaying in the Devfile registry

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/application-stack#211]
At the moment, Open Liberty does not show up in the Devfile registry under OpenShift. it turned out we need a sample that uses devfile 2.2.

See the following explaination:

> The current ODC queries the samples in the devfile registry. One thing to note is that ODC currently only supports the devfile 2.2 outer loop scenario. Open Liberty currently have a devfile 2.1 stack in devfile registry and that is being consumed by odo. In order to get Open Liberty to show on ODC, we'll need a Open Liberty sample that supports devfile 2.2 with the outer loop support.
> 
>  
> 
> The Open Liberty team worked on a version of stack with the outer loop support ([https://github.com/devfile/registry/pull/95](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_devfile_registry_pull_95&d=DwMDaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=Cgg3g_fs9ax5llvDrAM4caBmfiA1kT4cQBIdJQ9inpM&m=PoHRQWsQtpBHQynN2VzjbShxeUbGC-_as_GV7OdYtKeYIRji3rdF0pPVXIRrts0v&s=9hThfAslyJZgrAdR6aIF-TVjwkMKNGQJvQR2QJG8zJ0&e=)) before. We haven't merged that one yet since the devfile 2.2 spec has not been GA yet. We are currently only accepting devfile 2.2 samples for the time being. Therefore, the first step is to create a sample and include the devfile 2.2 as part of the sample. Once you have that, you can just submit a PR to add that to the samples list ([https://github.com/devfile/registry/blob/main/extraDevfileEntries.yaml](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_devfile_registry_blob_main_extraDevfileEntries.yaml&d=DwMDaQ&c=jf_iaSHvJObTbx-siA1ZOg&r=Cgg3g_fs9ax5llvDrAM4caBmfiA1kT4cQBIdJQ9inpM&m=PoHRQWsQtpBHQynN2VzjbShxeUbGC-_as_GV7OdYtKeYIRji3rdF0pPVXIRrts0v&s=GRpGZ80nsUDT-Sud3-NqBOJEfkTcFlN2Uy32jgg5aM8&e=)) in the devfile registry repo.
> 
>  
> 
> After that has been merged, it will show up automatically in ODC after we refresh the devfile registry.

**Comment by Emily-Jiang** [comment]
Which team should own this issue? I think it is in the roadmap but no one seems to claim it. @yeekangc @scottkurz any thoughts on this?

**Comment by yeekangc** [comment]
Closing per discussion with @NottyCode @gcharters.  Will file new epics for any future devfile work.
