### ISSUE TITLE
Document outer loop experience including Prometheus integration

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/application-stack#63]
Could be Open Shift only

No need to include DB yet (still prototyping).

Format TBD.  I think we need something more than README.md, but not sure exactly which format.  @awisniew90 let me know what you think.    We also want to get this reviewed by Don Bourne and team as we get closer.

**Comment by awisniew90** [comment]
I think the readme should have a basic mention of how to use "odo deploy" but should then have a link to a "guide" showing how to deploy and connect to prometheus.

**Comment by scottkurz** [comment]
Done here: https://github.com/OpenLiberty/application-stack/wiki/Deploy-an-Application-with-Metrics-Monitoring
